# DO NOT CHANGE THE NAME (e_demand),
#IF YOU WANT TO CHANGE THIS NAME, THEN YOU HAVE TO CHANGE THE EACH IMPORT STATEMENT IN THE CODE
#THIS NAME WILL NOT IMPACT IN YOUR APP, SO ITS NOT MANDATORY TO CHANGE IT
name: e_demand
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  # Flutter SDK dependencies
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_bloc: ^9.1.0

  # Internationalization & Localization
  intl: ^0.20.2

  # Firebase Services
  firebase_auth: ^6.1.0
  firebase_messaging: ^16.0.2
  firebase_analytics: ^12.0.2
  firebase_core: ^4.1.1

  # Authentication & Social Login
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^7.0.1

  # UI Components & Widgets
  pinput: ^5.0.2
  shimmer: ^3.0.0
  flutter_slidable: ^4.0.3
  flutter_svg: ^2.2.1
  #rive: ^0.13.4
  readmore: ^3.0.0
  flutter_widget_from_html: ^0.17.1
  carousel_slider: ^5.1.1
  toastification: ^3.0.3
  clarity_flutter: ^1.5.0

  # Storage & Database
  hive_flutter: ^1.1.0
  shared_preferences: ^2.5.3

  # Networking & HTTP
  dio: ^5.9.0
  http_parser: ^4.1.2
  mime: ^2.0.0

  # Image & Media Handling
  cached_network_image: ^3.4.1
  image_picker: ^1.2.0
  image_cropper: ^11.0.0
  video_player: ^2.10.0
  lottie: ^3.3.2

  # Location & Maps
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  google_maps_flutter: ^2.13.1
  custom_info_window: ^1.0.1

  # Notifications
  awesome_notifications: ^0.10.1

  # Payments
  razorpay_flutter: ^1.4.0
  flutter_stripe: ^12.0.2

  # File & Path Management
  path_provider: ^2.1.5
  path: ^1.9.1
  external_path: ^2.2.0
  open_file: ^3.5.10
  file_picker: ^10.3.3

  # Web & URL Handling
  webview_flutter: ^4.13.0
  url_launcher: ^6.3.2
  any_link_preview: ^3.0.3

  # Device & System
  device_info_plus: ^12.1.0
  vibration: ^3.1.4
  quick_actions: ^1.1.0
  permission_handler: ^12.0.1

  # Utilities
  share_plus: ^12.0.0
  version: ^3.0.2
  package_info_plus: ^8.3.1

  # Advertising
  google_mobile_ads: ^6.0.0

  # Shader Effects
  flutter_shader_snap: ^0.0.3

  # Commented out packages (for reference)
  # cupertino_icons: ^1.0.2
  # connectivity_plus: ^6.0.5
  # hive: ^2.2.1
  # app_settings: ^6.1.1
  # firebase_core_platform_interface: ^5.3.0
  # google_fonts: ^6.2.1

dependency_overrides:
#  pin_input_text_field: "4.5.0"
#  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  change_app_package_name: ^1.5.0

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icons/app_logo_icon.png"
  adaptive_icon_foreground: "assets/icons/forground.png"
  adaptive_icon_background: "assets/icons/background.png"
  remove_alpha_ios: true
  # background_color_ios: "#FFC100"

flutter:
  uses-material-design: true
  shaders:
    - packages/flutter_shader_snap/shaders/split_snap_effect_shader.glsl # add if you use SnapShaderType.split (default)
    - packages/flutter_shader_snap/shaders/split_reversed_snap_effect_shader.glsl # add if you use SnapShaderType.splitReversed
    - packages/flutter_shader_snap/shaders/smoke_snap_effect_shader.glsl # add if you use SnapShaderType.smoke

  assets:
    - assets/languages/
    - assets/images/
    - assets/images/branding/
    - assets/images/flags/
    - assets/mapTheme/
    - assets/animation/

  fonts:
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-Black.ttf
          weight: 900
        - asset: assets/fonts/Lexend-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lexend-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Lexend-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Lexend-Light.ttf
          weight: 300
        - asset: assets/fonts/Lexend-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lexend-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lexend-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Lexend-Thin.ttf
          weight: 100
